---
name: ICP DFX Build Test

on: ["push", "pull_request"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./FoodHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.x
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Install NodeJS Dependencies
        run: |
          npm install
      - name: Install DFX
        uses: dfinity/setup-dfx@main
      - name: Build Check
        run: |
          dfx start --background
          dfx build --check
